---
title: "Lab2"
author: "Kosenko Oleksandr"
date: "2022-10-07"
output: html_document
---

1.  Створить вектор v із 100 елементів командою v \<- rnorm(100). Для цього вектору виведіть: 10-й елемент; елементи з 10-го по 20-й включно; 10 елементів починаючи з 20-го; елементи більше 0.

```{r, include=TRUE}
vector <- rnorm(100)
vector

vector[10]

vector[10:20]
 
vector[10:29]

vector[vector>0]
```

2.  Створіть фрейм (data frame) y командою y \<- data.frame(a = rnorm(100), b = 1:100, cc = sample(letters, 100, replace = TRUE)). Для цього data frame виведіть: останні 10 строк; строки з 10 по 20 включно; 10-й елемент стовпця b; повністю стовпець cc, при цьому використайте ім'я стовпця.

```{r, include=TRUE}
y <- data.frame(a = rnorm(100), b = 1:100, cc = sample(letters, 100, replace = TRUE))

y

y[90:100, ]

y[10:20, ]

y[10,"b"]

y[ ,"cc"]
```

3.  Створіть вектор z з елементами 1, 2, 3, NA, 4, NA, 5, NA. Для цього вектору: виведіть всі елементи, які не NA; підрахуйте середнє значення всіх елементів цього вектору без NA значень та з NA значеннями.

```{r, include=TRUE}
z<-c(1,2,3,NA,4,NA,5,NA)
z1<-is.na(z)

z1

z[!z1]


z2<-z[!z1]
mean(z2)

mean(z)

```
